# Generated by Django 5.1 on 2024-08-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(upload_to='blog/image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(upload_to='blog/image/%Y/%m/%d/'),
        ),
    ]
